### PR TITLE
Fix various typos and grammatical errors

### PR DESCRIPTION
**Pull request by ebiggers**

### CODE REVIEW

**Comment by josephlr** [comment]
Thanks for the PR! Were these changes manual or did you run a tool?

Can you rebase onto #142 (so that the CI is happy)?

**Comment by ebiggers** [comment]
> Thanks for the PR! Were these changes manual or did you run a tool?
> 
> Can you rebase onto #142 (so that the CI is happy)?

Done.

It was a combination of the two --- some found manually while reading parts of the code, and some found by a custom script that checks for some common errors, like [common mispellings](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/scripts/spelling.txt) and duplicated words.  My script produces some false positives and relies on external files, so we can't run it during CI unfortunately.

**Comment by ebiggers** [comment]
Added more information to the commit message.

**Comment by josephlr** [comment]
Thanks for this!!!

**Pull request merged**
