### PR TITLE
feat(spell-check): add make command for spell check.

### LINKED ISSUE #71: Get spelling linter
I cannot spell. Get a linter that runs as part of the CI process that checks for spelling errors.

### PR DESCRIPTION
**Pull request by fristonio**
* Remove spelling mistakes in the repository
* Add travis script to check for typos.
* Add command to Makefile to check for typos.
* Fixes #71

### CODE REVIEW

**Comment by fristonio** [comment]
@josephlr I used misspell to check for typos. I think it is mature enough to be used in our case. I haven't added any strict checks on spellings in CI(I don't want the builds to fail just because there was a typo in comment).
I think we can add a pre-commit hook for the Make command so this spell check runs for each commit.

**Comment by josephlr** [comment]
@fristonio Would it be possible for your changes here to match what we do with other linting tools?

#107 changes a lot about how we handle dev dependancies, so I'd want this change to basically just do what we are doing in that PR:
- Download and Build github.com/client9/misspell/cmd/misspell in the `Makefile` (we already have a bunch of tools in there like `golint`, `goimports`, etc...).
- Run the spell check as part of `make lint`. This also eliminates the need to check and see if the binary is actually present, the Makefile will do it for you.

**Comment by josephlr** [comment]
@fristonio This is really awesome though, I'm going to start using this tool on some of my other projects!!

**Comment by fristonio** [comment]
> Would it be possible for your changes here to match what we do with other linting tools?

Yeah I will update the Pull request once #107 is merged to master. This won't be much work.

> This is really awesome though, I'm going to start using this tool on some of my other projects!!

Yeah the tool is really great, I use it for my personal projects too.

**Pull request merged**
